### ISSUE TITLE
Missing blog links

### ISSUE THREAD

**Issue by RobertKomara** [dselivanov/dselivanov.github.io#1]
Hi there! I'm getting a 404 on two blog posts over the last few days:

http://dsnotes.com/post/2017-01-27-lessons-learned-from-outbrain-click-prediction-kaggle-competition/
http://dsnotes.com/post/2017-02-07-large-data-feature-hashing-and-online-learning-part-2/

Do you mind checking in on the links?

**Comment by dselivanov** [comment]
Thanks  for report - fixed now (missed these posts during migration). Also now need to use `https://` prefix.
