### ISSUE TITLE
missing link for Fitting logistic regression on 100gb dataset on a laptop

### ISSUE THREAD

**Issue by Sandy4321** [dselivanov/dselivanov.github.io#3]
http://dsnotes.com/post/2017-02-07-large-data-feature-hashing-and-online-learning-part-2/

Fitting logistic regression on 100gb dataset on a laptop

**Comment by dselivanov** [comment]
Thanks for report. Fixed now. Also now with `https://` prefix. Don't know why does one link doesn't work with plain `http://`

**Comment by Sandy4321** [comment]
great thanks
